package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, November 11, 2014 7:25:31 PM IST
*/

public interface HelloOperations 
{
  String getRecord (String email);
  String insertRecord (String fn, String ln, String phn, String email, String city, String state);
  String deleteRecord (String phn);
} // interface HelloOperations
